### ISSUE TITLE
Atualizar modelagem e corrigir documentação de Arquitetura

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#129]
# Atualizar modelagem e corrigir documentação de Arquitetura

## Descrição

A documentação deve ser atualizada com as mudanças que ocorreram na modelagem do Banco de Dados. Também é necessário corrigir um Diagrama de Casos de Uso que não existe no projeto.
  
## Critérios de aceitação

- [x] fga-eps-mds/2022-2-CAPJu-Doc#124
- [x] fga-eps-mds/2022-2-CAPJu-Doc#128
- [x] fga-eps-mds/2022-2-CAPJu-Doc#130

Closes: fga-eps-mds/2022-2-CAPJu-Doc#124
Closes: fga-eps-mds/2022-2-CAPJu-Doc#128
Closes: fga-eps-mds/2022-2-CAPJu-Doc#130
