### ISSUE TITLE
[Tarefa - 03] Configurar etiquetas no Github

### ISSUE THREAD

**Issue by DaviAntonio** [fga-eps-mds/2022-2-CAPJu-Doc#33]
# [Tarefa - 03] Configurar etiquetas no Github

## Descrição

É necessário configurar as etiquetas, também chamadas de rótulos, para marcar as *issues* do Github conforme o padrão da disciplina.

## Critérios de aceitação

- [x] Documentar os rótulos #34 

As seguintes etiquetas padrões do Github devem existir:
- [x] bug
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] documentation
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
      - [x] Modificar de `Documentação` para `documentation` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
      - [x] Modificar de `documentação` para `documentation` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
      - [x] Modificar de `documentação` para `documentation` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
      - [x] Modificar de `Documentation` para `documentation` 
- [x] duplicate
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] enhancement
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
    - [x] Modificar de `Melhoria` para `enhancement` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
    - [x] Modificar de `Melhorias` para `enhancement` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
    - [x] Modificar de `Melhorias` para `enhancement` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
    - [x] Modificar de `Melhorias` para `enhancement` 
- [x] good first issue
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] help wanted
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] invalid
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] question
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] wontfix
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 

As seguintes etiquetas personalizadas devem existir com as cores especificadas abaixo:
- [x] HOTFIX : #d73a4a
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] DOCS :   #0075ca
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] FEATURE : #094EF2
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
    - [x] Corrigir cor de `#6C8A06` para `#094EF2` 
    - [x] Renomear de `feat` para `FEATURE`
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] US : #BE71F6
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
    - [x] Corrigir cor de `#5319E7` para `#BE71F6` 
    - [x] Renomear de `HU` para `US`
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
    - [x] Corrigir cor de `#5319E7` para `#BE71F6` 
    - [x] Renomear de `HU` para `US`
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
    - [x] Corrigir cor de `#5319E7` para `#BE71F6` 
    - [x] Renomear de `HU` para `US`
- [x] ARQ : #0D5571
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] DEVOPS :  #9014A0
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] ANALYTICS : #12477F
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] EASY :  #C5DEF5
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] MEDIUM : #BFD4F2
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] HARD :  #D4C5F9
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
- [x] EPS  : #006633
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
    - [x] Corrigir cor de `#008672` para `#006633` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
    - [x] Corrigir cor de `#008672` para `#006633` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
    - [x] Corrigir cor de `#008672` para `#006633` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
    - [x] Corrigir cor de `#008672` para `#006633` 
- [x] MDS : #0068b4
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Doc
    - [x] Corrigir cor de `#7057ff` para `#0068b4`
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Interface
    - [x] Corrigir cor de `#7057ff` para `#0068b4` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-Service
    - [x] Corrigir cor de `#7057ff` para `#0068b4` 
  - [x] https://github.com/fga-eps-mds/2022-2-CAPJu-User 
    - [x] Corrigir cor de `#7057ff` para `#0068b4` 

## Informações adicionais

Código original especificando as etiquetas:
```
LABELS COLORS = {
    HOTFIX : #d73a4a
    DOCS :   #0075ca
    FEATURE : #094EF2
    US : #BE71F6
    ARQ : #0D5571
    DEVOPS :  #9014A0
    ANALYTICS : #12477F
    EASY :  #C5DEF5
    MEDIUM : #BFD4F2
    HARD :  #D4C5F9
    EPS  : #006633
    MDS : #0068b4
}
```

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Doc/33?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
